version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./
    environment:
      ELASTICSEARCH_HOST: "localhost:9200"
    ports:
      - "4000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    links:
      - mongo
  redis:
    image: "redis:latest"
  mongo:
    container_name: mongo
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      # - "9300:9300"
    networks:
      - esnet
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
    driver: local
networks:
  esnet:
  # server:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: .
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
